version: '3.1'
services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: /run/secrets/db_password
      POSTGRES_DB: bookstore
    ports:
      - "5432:5432"
    secrets:
      - db_password
secrets:
  db_password:
    file: db_password.txt
